# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffa2e308c16c4ecf9ada5913e00ad95970b0b9554435c12bfc4be7abcd69564a97545db638a80770748d48124d4dce03f4bcb1736cf245b03ee47452bb2c5164

test:
  secret_key_base: dedd677c5424f964e4577c4868dc19b29013894d45573f25fd1eedc76f9d9ffa0dcc30015d33d41b4f7e28b081ec8e7a47c3fad4f2e2d8bca50eaae82995f9db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
